### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by bmvantunes** [aryanvikash/aryanvikash.com#1]
Hello my friend,

I only saw your youtube comment right now :) 
I was able to fix your problems, basically you had your CustomHeader in the wrong place :)

I created a codesandbox with your code =)
Let me know if you understand what I changed :)

https://codesandbox.io/s/intelligent-ishizaka-styq7?file=/pages/_app.js

Bruno

**Comment by aryanvikash** [comment]
@bmvantunes  Thanks a lot I was Trying to fix it for the last 3 Days. :heart: 

 But can You explain a little bit why that thing was not Working on _document.js  :smile:
